server:
  port: 8080

spring:
  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  cache:
    type: none

  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root

logging:
  level:
    ROOT: INFO

    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG

    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
